In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import pylab
import sys

pylab.rcParams['figure.figsize'] = (10.0, 8.0)

In [9]:
# verify that an RNN can accumulate its inputs
import numpy
import theano
import theano.tensor as T
from blocks.bricks.recurrent import SimpleRecurrent
from blocks.graph import ComputationGraph
from blocks import initialization
from blocks.bricks import Identity

In [10]:
x = tensor.tensor3('x')
rnn = SimpleRecurrent(
    dim=3, activation=Identity(), weights_init=initialization.Identity())
rnn.initialize()
h = rnn.apply(x)    
    
f = theano.function([x], h)
print(f(numpy.ones((3, 1, 3), dtype=theano.config.floatX))) 

[[[ 1.  1.  1.]]

 [[ 2.  2.  2.]]

 [[ 3.  3.  3.]]]


### Challenge:
    
(1)
- what do the 3 dimensions of the numpy.ones matrix represent? (hint: (batch, features, time), but in what order?
- you can check the implementation of the SimpleRecurrent transition here: https://github.com/mila-udem/blocks/blob/master/blocks/bricks/recurrent.py#L322-L323